
package view;

import DAO.AddStockDAO;
import javax.swing.JOptionPane;
import model.AddStock;
/**
 *
 * @author Jotamo Jr
 */
public class StockForm extends javax.swing.JFrame {

    /**
     * Creates new form ProdutoForm
     */
    public StockForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCbChaveSimples = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jQtdChaveSimples = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCbChaveCarro = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jQtdChaveCarro = new javax.swing.JTextField();
        btnRegistar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Chave Simples: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jCbChaveSimples.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "050", "051", "054", "058", "Viru", "GL7", "TL8", "TL8R", "LU2", "Gerax" }));
        jCbChaveSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbChaveSimplesActionPerformed(evt);
            }
        });
        jCbChaveSimples.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCbChaveSimplesKeyPressed(evt);
            }
        });
        getContentPane().add(jCbChaveSimples, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 130, -1));

        jLabel2.setText("Quantidade: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jQtdChaveSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQtdChaveSimplesActionPerformed(evt);
            }
        });
        jQtdChaveSimples.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jQtdChaveSimplesKeyPressed(evt);
            }
        });
        getContentPane().add(jQtdChaveSimples, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 130, -1));

        jLabel3.setText("Chave de Carro: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jCbChaveCarro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toy 15 - Ferro", "Toy 15 - Boracha", "Toy 9", "Toy 10", "Toy 29R", "Toy 48R", "DAT 15", "MATE 6" }));
        jCbChaveCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbChaveCarroActionPerformed(evt);
            }
        });
        jCbChaveCarro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCbChaveCarroKeyPressed(evt);
            }
        });
        getContentPane().add(jCbChaveCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 130, -1));

        jLabel4.setText("Quantidade: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jQtdChaveCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQtdChaveCarroActionPerformed(evt);
            }
        });
        jQtdChaveCarro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jQtdChaveCarroKeyPressed(evt);
            }
        });
        getContentPane().add(jQtdChaveCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 130, -1));

        btnRegistar.setText("Registar");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pexels-photo-101808.jpeg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        // TODO add your handling code here:
        adicionarProduto();
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void jQtdChaveSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQtdChaveSimplesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQtdChaveSimplesActionPerformed

    private void jQtdChaveCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQtdChaveCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQtdChaveCarroActionPerformed

    private void jCbChaveSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbChaveSimplesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbChaveSimplesActionPerformed

    private void jCbChaveCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbChaveCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbChaveCarroActionPerformed

    private void jCbChaveSimplesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCbChaveSimplesKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            jQtdChaveSimples.requestFocus();
        }
    }//GEN-LAST:event_jCbChaveSimplesKeyPressed

    private void jQtdChaveSimplesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQtdChaveSimplesKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            jCbChaveCarro.requestFocus();
        }
    }//GEN-LAST:event_jQtdChaveSimplesKeyPressed

    private void jQtdChaveCarroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQtdChaveCarroKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            btnRegistar.requestFocus();
            adicionarProduto();
        }
    }//GEN-LAST:event_jQtdChaveCarroKeyPressed

    private void jCbChaveCarroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCbChaveCarroKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            jQtdChaveCarro.requestFocus();
        }
    }//GEN-LAST:event_jCbChaveCarroKeyPressed

    /**
     * @param args the command line arguments
     */
    
    public static boolean validarNumeros(String dados){
        
        return dados.matches("[0-9]*");
    }
    
    public void adicionarProduto(){
        
        String chaveSimples = (String) jCbChaveSimples.getSelectedItem();
        String qtdChaveSimples = jQtdChaveSimples.getText();
        String chaveCarro = jCbChaveSimples.getSelectedItem().toString();
        String qtdChaveCarro = jQtdChaveCarro.getText();
        
        AddStock add = new AddStock(chaveSimples, qtdChaveSimples, chaveCarro, qtdChaveCarro);
        
        if(chaveSimples.isEmpty() || qtdChaveSimples.isEmpty() || chaveCarro.isEmpty() || qtdChaveCarro.isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos");
            }
        
        if(!validarNumeros(qtdChaveSimples.trim())){
            JOptionPane.showMessageDialog(null, "Digite quantidade valida");
        } 
        
        if(!validarNumeros(qtdChaveCarro.trim())){
            JOptionPane.showMessageDialog(null, "Digite quantidade valida");
        }
        
        AddStockDAO dao = new AddStockDAO();
        dao.save(add);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistar;
    private javax.swing.JComboBox<String> jCbChaveCarro;
    private javax.swing.JComboBox<String> jCbChaveSimples;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jQtdChaveCarro;
    private javax.swing.JTextField jQtdChaveSimples;
    // End of variables declaration//GEN-END:variables
}
