/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Jotamo Jr
 */
public class TelaP extends javax.swing.JFrame {

    /**
     * Creates new form TelaP
     */
    boolean a=true;
    public TelaP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void hideShowMenu(JPanel menuShowHide, boolean dashboard){
        if(dashboard == true){
            menuShowHide.setPreferredSize(new Dimension(50, menuShowHide.getHeight()));
            changeIcon(menu,"/Images/back_45px.png");
        } else{
            menuShowHide.setPreferredSize(new Dimension(270, menuShowHide.getHeight()));
            changeIcon(menu,"/Images/back_45px.png");
        }
    }
    
    public void ChangeColor(JPanel painel,Color cor){
        painel.setBackground(cor);
    }
    
    public void clickmenu(JPanel h1,int numberbool){
        if(numberbool==1){
            h1.setBackground(new Color(245,239,239));
            
        }else{
            h1.setBackground(new Color(86,86,86));
            
        }
    }
    
    public void changeIcon(JLabel button,String source){
        ImageIcon img = new ImageIcon(getClass().getResource(source));
        button.setIcon(img);
    }
                                                                  
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        ImageIcon icon = new ImageIcon(getClass().getResource("1opcao.jpg"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        }
        ;
        sideFirstPanel = new javax.swing.JPanel();
        sideSecPanel = new javax.swing.JPanel();
        menuShowHide = new javax.swing.JPanel();
        menu = new javax.swing.JLabel();
        homeButton = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        resButton = new javax.swing.JPanel();
        reservas = new javax.swing.JLabel();
        hospButton = new javax.swing.JPanel();
        hospedagem = new javax.swing.JLabel();
        HospedeButton = new javax.swing.JPanel();
        clients = new javax.swing.JLabel();
        userButton = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lockButton = new javax.swing.JPanel();
        lock = new javax.swing.JLabel();
        inButton = new javax.swing.JPanel();
        in = new javax.swing.JLabel();
        outButton = new javax.swing.JPanel();
        out = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        dashboard = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        data = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        iconClose = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        jClose = new javax.swing.JLabel();
        btnMax = new javax.swing.JPanel();
        jMax = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.BorderLayout());

        jDesktopPane1.setLayout(new java.awt.BorderLayout());

        //jPanel1.setBackground(new Color(238,225,225,1));
        sideFirstPanel.setBackground(new java.awt.Color(194, 194, 194,1));
        sideFirstPanel.setPreferredSize(new java.awt.Dimension(100, 588));
        sideFirstPanel.setLayout(new java.awt.BorderLayout());

        sideSecPanel.setBackground(new java.awt.Color(255, 255, 255));
        sideSecPanel.setPreferredSize(new java.awt.Dimension(300, 588));
        sideSecPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuShowHide.setAlignmentY(5.0F);
        menuShowHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuShowHideMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuShowHideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuShowHideMouseExited(evt);
            }
        });

        menu.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        menu.setForeground(new java.awt.Color(86, 86, 86));
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/navigation-menu-4.png"))); // NOI18N
        menu.setText("          Menu");

        javax.swing.GroupLayout menuShowHideLayout = new javax.swing.GroupLayout(menuShowHide);
        menuShowHide.setLayout(menuShowHideLayout);
        menuShowHideLayout.setHorizontalGroup(
            menuShowHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuShowHideLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuShowHideLayout.setVerticalGroup(
            menuShowHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuShowHideLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(menu)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        sideSecPanel.add(menuShowHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 320, 70));

        homeButton.setPreferredSize(new java.awt.Dimension(320, 70));
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButtonMouseExited(evt);
            }
        });

        home.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        home.setForeground(new java.awt.Color(82, 82, 82));
        home.setText("          Home");

        javax.swing.GroupLayout homeButtonLayout = new javax.swing.GroupLayout(homeButton);
        homeButton.setLayout(homeButtonLayout);
        homeButtonLayout.setHorizontalGroup(
            homeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeButtonLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );
        homeButtonLayout.setVerticalGroup(
            homeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeButtonLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(home)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        sideSecPanel.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 320, -1));

        resButton.setPreferredSize(new java.awt.Dimension(141, 45));
        resButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resButtonMouseExited(evt);
            }
        });

        reservas.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        reservas.setForeground(new java.awt.Color(82, 82, 82));
        reservas.setText("         Reservas");

        javax.swing.GroupLayout resButtonLayout = new javax.swing.GroupLayout(resButton);
        resButton.setLayout(resButtonLayout);
        resButtonLayout.setHorizontalGroup(
            resButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resButtonLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(reservas)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        resButtonLayout.setVerticalGroup(
            resButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(125, 125, 125))
        );

        sideSecPanel.add(resButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 155, 320, 70));

        hospButton.setPreferredSize(new java.awt.Dimension(320, 70));
        hospButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hospButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hospButtonMouseExited(evt);
            }
        });

        hospedagem.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        hospedagem.setForeground(new java.awt.Color(82, 82, 82));
        hospedagem.setText("         Hospedagem");

        javax.swing.GroupLayout hospButtonLayout = new javax.swing.GroupLayout(hospButton);
        hospButton.setLayout(hospButtonLayout);
        hospButtonLayout.setHorizontalGroup(
            hospButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospButtonLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(hospedagem)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        hospButtonLayout.setVerticalGroup(
            hospButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hospedagem)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        sideSecPanel.add(hospButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 320, -1));

        HospedeButton.setPreferredSize(new java.awt.Dimension(320, 70));
        HospedeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HospedeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HospedeButtonMouseExited(evt);
            }
        });

        clients.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        clients.setForeground(new java.awt.Color(82, 82, 82));
        clients.setText("         Hospedes");

        javax.swing.GroupLayout HospedeButtonLayout = new javax.swing.GroupLayout(HospedeButton);
        HospedeButton.setLayout(HospedeButtonLayout);
        HospedeButtonLayout.setHorizontalGroup(
            HospedeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HospedeButtonLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(clients)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        HospedeButtonLayout.setVerticalGroup(
            HospedeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HospedeButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clients)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        sideSecPanel.add(HospedeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 305, 320, -1));

        userButton.setPreferredSize(new java.awt.Dimension(320, 70));
        userButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userButtonMouseExited(evt);
            }
        });

        user.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        user.setForeground(new java.awt.Color(82, 82, 82));
        user.setText("          Users");

        javax.swing.GroupLayout userButtonLayout = new javax.swing.GroupLayout(userButton);
        userButton.setLayout(userButtonLayout);
        userButtonLayout.setHorizontalGroup(
            userButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userButtonLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        userButtonLayout.setVerticalGroup(
            userButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        sideSecPanel.add(userButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 320, -1));

        jPanel12.setBackground(new java.awt.Color(82, 82, 82));
        jPanel12.setPreferredSize(new java.awt.Dimension(250, 165));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lockButton.setBackground(new java.awt.Color(82, 82, 82));
        lockButton.setForeground(new java.awt.Color(255, 255, 255));
        lockButton.setPreferredSize(new java.awt.Dimension(250, 55));
        lockButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lockButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lockButtonMouseExited(evt);
            }
        });

        lock.setForeground(new java.awt.Color(245, 239, 239));
        lock.setText("            Lock");

        javax.swing.GroupLayout lockButtonLayout = new javax.swing.GroupLayout(lockButton);
        lockButton.setLayout(lockButtonLayout);
        lockButtonLayout.setHorizontalGroup(
            lockButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lockButtonLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lock, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        lockButtonLayout.setVerticalGroup(
            lockButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lockButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lock)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel12.add(lockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        inButton.setBackground(new java.awt.Color(82, 82, 82));
        inButton.setForeground(new java.awt.Color(255, 255, 255));
        inButton.setPreferredSize(new java.awt.Dimension(141, 45));
        inButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inButtonMouseExited(evt);
            }
        });

        in.setForeground(new java.awt.Color(245, 239, 239));
        in.setText("           Sign in");

        javax.swing.GroupLayout inButtonLayout = new javax.swing.GroupLayout(inButton);
        inButton.setLayout(inButtonLayout);
        inButtonLayout.setHorizontalGroup(
            inButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inButtonLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(in)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        inButtonLayout.setVerticalGroup(
            inButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inButtonLayout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addComponent(in))
        );

        jPanel12.add(inButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 240, 50));

        outButton.setBackground(new java.awt.Color(82, 82, 82));
        outButton.setForeground(new java.awt.Color(255, 255, 255));
        outButton.setPreferredSize(new java.awt.Dimension(250, 55));
        outButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                outButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                outButtonMouseExited(evt);
            }
        });

        out.setForeground(new java.awt.Color(245, 239, 239));
        out.setText("          Sign out");

        javax.swing.GroupLayout outButtonLayout = new javax.swing.GroupLayout(outButton);
        outButton.setLayout(outButtonLayout);
        outButtonLayout.setHorizontalGroup(
            outButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outButtonLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(out)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        outButtonLayout.setVerticalGroup(
            outButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outButtonLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(out)
                .addContainerGap())
        );

        jPanel12.add(outButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("            Username");
        jPanel12.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 180, 210, -1));

        sideSecPanel.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 320, 220));

        sideFirstPanel.add(sideSecPanel, java.awt.BorderLayout.CENTER);

        footer.setPreferredSize(new java.awt.Dimension(350, 50));

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        sideFirstPanel.add(footer, java.awt.BorderLayout.PAGE_END);

        jDesktopPane1.add(sideFirstPanel, java.awt.BorderLayout.LINE_START);

        dashboard.setBackground(new Color(0,0,0,1));
        dashboard.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(658, 50));

        data.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        data.setForeground(new java.awt.Color(86, 86, 86));
        data.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(760, Short.MAX_VALUE)
                .addComponent(data)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(data)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        dashboard.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jDesktopPane1.add(dashboard, java.awt.BorderLayout.CENTER);

        mainPanel.add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        header.setBackground(new java.awt.Color(153, 153, 153));
        header.setPreferredSize(new java.awt.Dimension(803, 50));
        header.setLayout(new java.awt.BorderLayout());

        iconClose.setBackground(new java.awt.Color(153, 153, 153));
        iconClose.setPreferredSize(new java.awt.Dimension(155, 37));
        iconClose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setBackground(new java.awt.Color(102, 102, 102));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });

        jClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete-sign (1).png"))); // NOI18N

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jClose, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addComponent(jClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        iconClose.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 40));

        btnMax.setBackground(new java.awt.Color(102, 102, 102));
        btnMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaxMouseExited(evt);
            }
        });

        jMax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/full-screen (1)_1.png"))); // NOI18N

        javax.swing.GroupLayout btnMaxLayout = new javax.swing.GroupLayout(btnMax);
        btnMax.setLayout(btnMaxLayout);
        btnMaxLayout.setHorizontalGroup(
            btnMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMaxLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jMax, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnMaxLayout.setVerticalGroup(
            btnMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMaxLayout.createSequentialGroup()
                .addComponent(jMax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        iconClose.add(btnMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 50, 40));

        header.add(iconClose, java.awt.BorderLayout.LINE_END);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/geography.png"))); // NOI18N
        jLabel6.setText("CHAVES");

        jTextField1.setBackground(new java.awt.Color(153, 153, 150));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-pesquisar-30.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(99, 99, 99)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(0, 367, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        header.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuShowHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuShowHideMouseClicked

        if(a==true){
            hideShowMenu(sideFirstPanel,a);
            SwingUtilities.updateComponentTreeUI(this);
            a=false;
        }else{
            hideShowMenu(sideFirstPanel,a);
            SwingUtilities.updateComponentTreeUI(this);
            // HideMenu.setBackground(new Color(7,10,55));
            a=true;
        }

    }//GEN-LAST:event_menuShowHideMouseClicked

    private void menuShowHideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuShowHideMouseEntered
        // TODO add your handling code here:
        menuShowHide.setBackground(new Color(86,86,86));
        menu.setForeground(new Color(214, 217, 223));
        //  menu.setIcon(new Icon());
    }//GEN-LAST:event_menuShowHideMouseEntered

    private void menuShowHideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuShowHideMouseExited
        // TODO add your handling code here:
        menuShowHide.setBackground(new Color(214, 217, 223));
        menu.setForeground(new Color(86,86,86));
    }//GEN-LAST:event_menuShowHideMouseExited

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_homeButtonMouseClicked

    private void homeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseEntered
     
    }//GEN-LAST:event_homeButtonMouseEntered

    private void homeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseExited
        
    }//GEN-LAST:event_homeButtonMouseExited

    private void resButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resButtonMouseEntered
      
    }//GEN-LAST:event_resButtonMouseEntered

    private void resButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resButtonMouseExited
        
    }//GEN-LAST:event_resButtonMouseExited

    private void hospButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospButtonMouseEntered
        
    }//GEN-LAST:event_hospButtonMouseEntered

    private void hospButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospButtonMouseExited
       
    }//GEN-LAST:event_hospButtonMouseExited

    private void HospedeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HospedeButtonMouseEntered
        
    }//GEN-LAST:event_HospedeButtonMouseEntered

    private void HospedeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HospedeButtonMouseExited
        
    }//GEN-LAST:event_HospedeButtonMouseExited

    private void userButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseEntered
        
    }//GEN-LAST:event_userButtonMouseEntered

    private void userButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseExited
        
    }//GEN-LAST:event_userButtonMouseExited

    private void lockButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lockButtonMouseEntered
        ChangeColor(lockButton,new Color(179, 181, 183));
    }//GEN-LAST:event_lockButtonMouseEntered

    private void lockButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lockButtonMouseExited
        ChangeColor(lockButton,new Color(82, 82, 82));
    }//GEN-LAST:event_lockButtonMouseExited

    private void inButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inButtonMouseEntered
        // TODO add your handling code here:
        ChangeColor(inButton,new Color(179, 181, 183));

    }//GEN-LAST:event_inButtonMouseEntered

    private void inButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inButtonMouseExited
        ChangeColor(inButton,new Color(82, 82, 82));
    }//GEN-LAST:event_inButtonMouseExited

    private void outButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outButtonMouseEntered
        ChangeColor(outButton,new Color(179, 181, 183));
    }//GEN-LAST:event_outButtonMouseEntered

    private void outButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outButtonMouseExited
        ChangeColor(outButton,new Color(82, 82, 82));
    }//GEN-LAST:event_outButtonMouseExited

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        // TODO add your handling code here:
        btnClose.setBackground(Color.red);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        // TODO add your handling code here:
        btnClose.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnMaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaxMouseClicked
        // TODO add your handling code here:
        if(this.getExtendedState() != TelaPrincipall.MAXIMIZED_BOTH){
            this.setExtendedState(TelaPrincipall.MAXIMIZED_BOTH);
        } else{
            this.setExtendedState(TelaPrincipall.NORMAL);
        }
    }//GEN-LAST:event_btnMaxMouseClicked

    private void btnMaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaxMouseEntered
        // TODO add your handling code here:
        btnMax.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_btnMaxMouseEntered

    private void btnMaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaxMouseExited
        // TODO add your handling code here:
        btnMax.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btnMaxMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HospedeButton;
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnMax;
    private javax.swing.JLabel clients;
    private javax.swing.JDesktopPane dashboard;
    private javax.swing.JLabel data;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel home;
    private javax.swing.JPanel homeButton;
    private javax.swing.JPanel hospButton;
    private javax.swing.JLabel hospedagem;
    private javax.swing.JPanel iconClose;
    private javax.swing.JLabel in;
    private javax.swing.JPanel inButton;
    private javax.swing.JLabel jClose;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jMax;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lock;
    private javax.swing.JPanel lockButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel menu;
    private javax.swing.JPanel menuShowHide;
    private javax.swing.JLabel out;
    private javax.swing.JPanel outButton;
    private javax.swing.JPanel resButton;
    private javax.swing.JLabel reservas;
    private javax.swing.JPanel sideFirstPanel;
    private javax.swing.JPanel sideSecPanel;
    private javax.swing.JLabel user;
    private javax.swing.JPanel userButton;
    // End of variables declaration//GEN-END:variables
}
