
package view;

import DAO.UsuarioDAO;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author Jotamo Jr
 */
public class UserForm extends javax.swing.JFrame {

    /**
     * Creates new form UserForm
     */
    public UserForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jApelido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSenha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jConfirmPass = new javax.swing.JPasswordField();
        btnRegistar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registo de Funcionario");
        setMinimumSize(new java.awt.Dimension(680, 370));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, -1));

        jNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNomeKeyPressed(evt);
            }
        });
        getContentPane().add(jNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 159, 28));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Apelido:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 139, -1));

        jApelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jApelidoKeyPressed(evt);
            }
        });
        getContentPane().add(jApelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Username:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 159, -1));

        jUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsernameActionPerformed(evt);
            }
        });
        jUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jUsernameKeyPressed(evt);
            }
        });
        getContentPane().add(jUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 159, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Telefone:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 164, -1));

        jTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTelefoneKeyPressed(evt);
            }
        });
        getContentPane().add(jTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 160, 28));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 159, -1));

        jSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(jSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 159, 35));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Confirmar password:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 164, -1));

        jConfirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfirmPassActionPerformed(evt);
            }
        });
        jConfirmPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jConfirmPassKeyPressed(evt);
            }
        });
        getContentPane().add(jConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 160, 30));

        btnRegistar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegistar.setText("Registar");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 110, 41));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/single-neutral-actions-add.png"))); // NOI18N
        jLabel7.setText("Registo de Funcionario");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 14, 230, 30));

        lblData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblData.setText("Data: ");
        getContentPane().add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pexels-photo-3828944 (1).jpeg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameActionPerformed

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        registar();
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void jNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNomeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            jApelido.requestFocus();
        }
    }//GEN-LAST:event_jNomeKeyPressed

    private void jUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsernameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            jTelefone.requestFocus();
        }
    }//GEN-LAST:event_jUsernameKeyPressed

    private void jApelidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jApelidoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            jUsername.requestFocus();
        }
    }//GEN-LAST:event_jApelidoKeyPressed

    private void jTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTelefoneKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            jSenha.requestFocus();
        }
    }//GEN-LAST:event_jTelefoneKeyPressed

    private void jSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSenhaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            jConfirmPass.requestFocus();
        }
    }//GEN-LAST:event_jSenhaKeyPressed

    private void jConfirmPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jConfirmPassKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            btnRegistar.requestFocus();
            registar();
        }
    }//GEN-LAST:event_jConfirmPassKeyPressed

    private void jConfirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfirmPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jConfirmPassActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Date data = new Date();
        DateFormat f = DateFormat.getDateInstance(DateFormat.LONG);
        lblData.setText(f.format(data));
    }//GEN-LAST:event_formWindowActivated
    
    public static boolean validarNumeros(String dados){
        
        return dados.matches("[0-9]*");
    } 
    
    public static boolean validarLetras(String dados){
        
        return dados.matches("[a-zA-Z]*");
    } 
    
    public void registar(){
        String nome = jNome.getText();
        String userName = jUsername.getText();
        String apelido = jApelido.getText();
        String cell = jTelefone.getText();
        String senha = jSenha.getText();
        String confirmarSenha = jConfirmPass.getText();
       
        Usuario user = new Usuario(nome, userName, apelido, cell, senha);
        
        if(!validarNumeros(cell.trim())){
            JOptionPane.showMessageDialog(null, "Digite numeros validos");
        }
        
        if(!validarLetras(nome.trim())){
            JOptionPane.showMessageDialog(null, "Digite nome valido");
        }
        
        if(!validarLetras(apelido.trim())){
            JOptionPane.showMessageDialog(null, "Digite apelido valido");
        }
        
        if(nome.isEmpty() || userName.isEmpty() || apelido.isEmpty() || cell.isEmpty() || senha.isEmpty() || confirmarSenha.isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos");
            }
            else{
            if(senha.equals(confirmarSenha)){
                UsuarioDAO dao = new UsuarioDAO();
                dao.save(user);
            }else{
                JOptionPane.showMessageDialog(null, "As senhas devem ser identicas");
            }
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistar;
    private javax.swing.JTextField jApelido;
    private javax.swing.JPasswordField jConfirmPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNome;
    private javax.swing.JPasswordField jSenha;
    private javax.swing.JTextField jTelefone;
    private javax.swing.JTextField jUsername;
    private javax.swing.JLabel lblData;
    // End of variables declaration//GEN-END:variables
}
