/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import DAO.AddStockDAO;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.AddStock;

/**
 *
 * @author Jotamo Jr
 */
public class StockForm extends javax.swing.JFrame {

    /**
     * Creates new form StockForm
     */
    public StockForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public static boolean validarNumeros(String dados){
        
        return dados.matches("[0-9]*");
    }
    
    public void adicionarProduto(){
        
        String chaveSimples = (String) jCbChaveSimples.getSelectedItem();
        String qtdChaveSimples = jQtdChaveSimples.getText();
        String chaveCarro = jCbChaveSimples.getSelectedItem().toString();
        String qtdChaveCarro = jQtdChaveCarro.getText();
        
        AddStock add = new AddStock(chaveSimples, qtdChaveSimples, chaveCarro, qtdChaveCarro);
        
        if(chaveSimples.isEmpty() || qtdChaveSimples.isEmpty() || chaveCarro.isEmpty() || qtdChaveCarro.isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos");
            }
        
        if(!validarNumeros(qtdChaveSimples.trim())){
            JOptionPane.showMessageDialog(null, "Digite quantidade valida");
        } 
        
        if(!validarNumeros(qtdChaveCarro.trim())){
            JOptionPane.showMessageDialog(null, "Digite quantidade valida");
        }
        
        AddStockDAO dao = new AddStockDAO();
        dao.save(add);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jContainerStock = new javax.swing.JPanel();
        jQtdChaveCarro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jQtdChaveSimples = new javax.swing.JTextField();
        btnRegistar = new javax.swing.JButton();
        jCbChaveCarro = new javax.swing.JComboBox<>();
        jCbChaveSimples = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jQtdChaveCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQtdChaveCarroActionPerformed(evt);
            }
        });
        jQtdChaveCarro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jQtdChaveCarroKeyPressed(evt);
            }
        });

        jLabel1.setText("Chave Simples: ");

        jLabel3.setText("Chave de Carro: ");

        jLabel2.setText("Quantidade: ");

        jQtdChaveSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQtdChaveSimplesActionPerformed(evt);
            }
        });
        jQtdChaveSimples.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jQtdChaveSimplesKeyPressed(evt);
            }
        });

        btnRegistar.setText("Registar");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });

        jCbChaveCarro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toy 15 - Ferro", "Toy 15 - Boracha", "Toy 9", "Toy 10", "Toy 29R", "Toy 48R", "DAT 15", "MATE 6" }));
        jCbChaveCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbChaveCarroActionPerformed(evt);
            }
        });
        jCbChaveCarro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCbChaveCarroKeyPressed(evt);
            }
        });

        jCbChaveSimples.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "050", "051", "054", "058", "Viru", "GL7", "TL8", "TL8R", "LU2", "Gerax" }));
        jCbChaveSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbChaveSimplesActionPerformed(evt);
            }
        });
        jCbChaveSimples.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCbChaveSimplesKeyPressed(evt);
            }
        });

        jLabel4.setText("Quantidade: ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Chave simples", "Quantidade", "Chave carro", "Quantidade"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(375, 64));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jContainerStockLayout = new javax.swing.GroupLayout(jContainerStock);
        jContainerStock.setLayout(jContainerStockLayout);
        jContainerStockLayout.setHorizontalGroup(
            jContainerStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
            .addGroup(jContainerStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jContainerStockLayout.createSequentialGroup()
                    .addGap(0, 300, Short.MAX_VALUE)
                    .addGroup(jContainerStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jContainerStockLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(24, 24, 24)
                            .addComponent(jCbChaveSimples, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jContainerStockLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(37, 37, 37)
                            .addComponent(jQtdChaveSimples, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jContainerStockLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(17, 17, 17)
                            .addComponent(jCbChaveCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jContainerStockLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(37, 37, 37)
                            .addComponent(jQtdChaveCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jContainerStockLayout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(btnRegistar)))
                    .addGap(0, 301, Short.MAX_VALUE)))
        );
        jContainerStockLayout.setVerticalGroup(
            jContainerStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jContainerStockLayout.createSequentialGroup()
                .addContainerGap(420, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jContainerStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jContainerStockLayout.createSequentialGroup()
                    .addGap(0, 158, Short.MAX_VALUE)
                    .addGroup(jContainerStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jCbChaveSimples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(jContainerStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jContainerStockLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel2))
                        .addComponent(jQtdChaveSimples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(jContainerStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jCbChaveCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(jContainerStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jContainerStockLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel4))
                        .addComponent(jQtdChaveCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(46, 46, 46)
                    .addComponent(btnRegistar)
                    .addGap(0, 159, Short.MAX_VALUE)))
        );

        getContentPane().add(jContainerStock, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(831, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCbChaveSimplesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCbChaveSimplesKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            jQtdChaveSimples.requestFocus();
        }
    }//GEN-LAST:event_jCbChaveSimplesKeyPressed

    private void jCbChaveSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbChaveSimplesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbChaveSimplesActionPerformed

    private void jCbChaveCarroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCbChaveCarroKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            jQtdChaveCarro.requestFocus();
        }
    }//GEN-LAST:event_jCbChaveCarroKeyPressed

    private void jCbChaveCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbChaveCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbChaveCarroActionPerformed

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        // TODO add your handling code here:
        adicionarProduto();
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void jQtdChaveSimplesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQtdChaveSimplesKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            jCbChaveCarro.requestFocus();
        }
    }//GEN-LAST:event_jQtdChaveSimplesKeyPressed

    private void jQtdChaveSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQtdChaveSimplesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQtdChaveSimplesActionPerformed

    private void jQtdChaveCarroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQtdChaveCarroKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            btnRegistar.requestFocus();
            adicionarProduto();
        }
    }//GEN-LAST:event_jQtdChaveCarroKeyPressed

    private void jQtdChaveCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQtdChaveCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQtdChaveCarroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistar;
    private javax.swing.JComboBox<String> jCbChaveCarro;
    private javax.swing.JComboBox<String> jCbChaveSimples;
    private javax.swing.JPanel jContainerStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jQtdChaveCarro;
    private javax.swing.JTextField jQtdChaveSimples;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
